version: '3'
services:
  web: 
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /home/node/app/node_modules # Do NOT map a folder up against node_modules inside the container
      - .:/home/node/app # map th current directory outside the container the app folder inside the container