# FROM node:18-alpine

# WORKDIR '/app'

# COPY package.json .
# RUN npm install 

# COPY . .

# CMD ["npm", "run", "start"]

# To avoid permission error 
FROM node:18-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install
COPY --chown=node:node ./ ./

CMD ["npm", "start"]

# From the terminal
# docker run -it -p 3000:3000 -v /home/node/app/node_modules -v ~/my-project-directory:/home/node/app IMAGE_ID